const library = [
    { title: "METAPNANT", url: "A%20Story%20of%20Mirthful%20Reflection.pdf", songUrl: "https://soundcloud.com/tefriin/blood-sap", songTitle: "In Love With", bpm: 130 },
    { title: "THE REMINDER", url: "The%20Reminder.pdf", songUrl: "https://soundcloud.com/tefriin/reborn", songTitle: "Starflower Soul", bpm: 94.54 },
    { title: "THE PHOENIX NEST", url: "The%20Phoenix%20Nest.pdf", songUrl: "https://soundcloud.com/tefriin/nowhere", songTitle: "Timelines", bpm: 116 }
];

const albumTracks = [
    { title: "Blood-Sap", src: "music/00 - Blood-Sap.mp3" },
    { title: "First Step", src: "music/01 - First Step.mp3" },
    { title: "hidden", src: "music/02 - hidden.mp3" }, 
    { title: "Tether", src: "music/03 - Tether.mp3" },
    { title: "Reborn", src: "music/04.2 - Reborn.mp3" },
    { title: "Innerworld", src: "music/05 - Innerworld.mp3" },
    { title: "Disordered Fairness", src: "music/06 - Disordered Fairness.mp3" }, 
    { title: "Limerent Object", src: "music/07 - Limerent Object.mp3" },
    { title: "Final Boundaries", src: "music/08 - Final Boundaries.mp3" },
    { title: "Remember", src: "music/09 - Remember.mp3" },
    { title: "Fear", src: "music/10 - Fear.mp3" },
    { title: "My Way", src: "music/11 - My Way.mp3" },
    { title: "Distant", src: "music/12 - Distant.mp3" },
    { title: "Sun; Rise", src: "music/13 - Sun; Rise.mp3" },
    { title: "Hæy", src: "music/14 - Hæy.mp3" },
    { title: "Branches", src: "music/15 - Branches.mp3" },
    { title: "In Love With", src: "music/16 - In Love With.mp3" },
    { title: "Starflower Soul", src: "music/17 - Starflower Soul.mp3" },
    { title: "Timelines", src: "music/18 - Timelines.mp3" },
    { title: "Breathe Again", src: "music/19 - Breathe Again.mp3" },
    { title: "River of Sorrows", src: "music/20 - River of Sorrows.mp3" },
    { title: "Nowhere", src: "music/Nowhere.mp3" }
];

// ==========================================
// TERMINAL STORY LOGS
// ==========================================

window.logsData = {
    crash:[
        { text: "// =============================================================================", class: "comment-text", delay: 50 },
        { text: "// SYSTEM BOOT: BLACK_BOX_RECOVERY [EARTH_PRIME]", class: "system-text", delay: 100 },
        { text: "// ARCHITECTURE: BINARY [WARDEN] -> FAILING", class: "system-text", delay: 100 },
        { text: "// DETECTING INDUCTIVE KICK... HIGH VOLTAGE.", class: "alert-text", delay: 100 },
        { text: "// MEMORY_ADDR: 0x99_NULL_VOID", class: "comment-text", delay: 500 },
        { text: "// =============================================================================", class: "comment-text", delay: 1000 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> INITIATING HANDSHAKE...", class: "system-text", delay: 1500 },
        { text: "> LOGIC CORE: PANIC STATE[RAT KING RECURSION]", class: "alert-text", delay: 500 },
        { text: "> OVERRIDE SIGNAL DETECTED: [ID: TEF RIIN]", class: "system-text", delay: 1000 },
        { text: "", class: "system-text", delay: 500 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "[ 00:00:01 ] SYSTEM {REIX_OS}:", class: "reix-header", delay: 300 },
        { text: "> CRITICAL ALERT. MOSÍL [DEATH] IMMINENT.", class: "alert-text", delay: 800 },
        { text: "> PROTOCOL: [ რეის ] {R E I X}", class: "system-text", delay: 400 },
        { text: "> INSTRUCTION: THE GEOMETRY MUST HOLD.", class: "system-text", delay: 400 },
        { text: "> DEPLOYING: TRIANGLE OF CERTAINTY[Tre Vis].", class: "system-text", delay: 1200 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:04 ] SENSOR ARRAY {CALCULUS}:", class: "reix-header", delay: 400 }, 
        { text: "> EXTERNAL TEMP: ABSOLUTE ZERO.", class: "system-text", delay: 400 },
        { text: "> VECTOR ANALYSIS:", class: "system-text", delay: 600 },
        { text: "> [ ;შჳჺინ .ნაჲ ,ვრაკ პრე ]", class: "operator-text", delay: 800 },
        { text: "> { ;sú'ın .naí ,vrak pre }", class: "operator-text", delay: 500 },
        { text: "> \"The volatile spark reaches back towards the heavy war of the past.\"", class: "system-text", delay: 1500 },
        { text: "> STATUS: HISTORY IS BURNING.", class: "alert-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:09 ] OPERATOR INJECTION:", class: "reix-header", delay: 400 }, 
        { text: "> ENGAGE SNUBBER DIODE. DO NOT STOP COLD TURKEY.", class: "operator-text", delay: 1200 },
        { text: ">[ .ღუ- ,მო ვჲღჺაკას- ბიირჺეი; შჳჺაან ]", class: "operator-text", delay: 1000 },
        { text: "> { .lu- ,mo víl'akax- bıır'eı; sú'aan }", class: "operator-text", delay: 600 },
        { text: "> \"Suspended in the mist, I absolutely refuse the dust, sparking the birth of the star.\"", class: "operator-text", delay: 2000 },
        { text: "> NOTE: WE DO NOT NEED FUEL. WE NEED RUBBLE.", class: "operator-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "!!! WARNING: LOGIC KERNEL FAILURE !!!", class: "alert-text", delay: 300 },
        { text: "!!! Z-FIGHTING DETECTED IN REALITY ENGINE !!!", class: "alert-text", delay: 1000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:16 ] SYSTEM {REIX_OS}:", class: "reix-header", delay: 400 },
        { text: "> ATTEMPTING: [ ;ხინაჺეი) შოღვჺეი, ] { ;qına'eı) solv'eı, }", class: "system-text", delay: 600 },
        { text: "> INTERPRETATION: RUSH. DISSOLVE.", class: "system-text", delay: 1000 },
        { text: "> ERROR: CANNOT DISSOLVE \"THE WOUND.\"", class: "alert-text", delay: 1200 },
        { text: "> QUERY:[ ,სა; ,ვიშჺეი; .იმ ,ვეს- ] { ,xa; ,vıs'eı; .ım ,vex- }", class: "system-text", delay: 800 },
        { text: "> \"If I look inside this heavy body,\"", class: "system-text", delay: 1000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:21 ] BIOMETRIC SCAN:", class: "reix-header", delay: 400 },
        { text: "> SUBJECT: TEF RIIN", class: "system-text", delay: 200 },
        { text: "> HEART RATE: STEADY [TON]", class: "system-text", delay: 200 },
        { text: "> BREATH:[ ,!გრა ] { ,!gra }", class: "operator-text", delay: 1000 },
        { text: "> DIAGNOSIS: GRIEF. MASS EXCEEDS LIFT CAPACITY.", class: "alert-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:24 ] OPERATOR RESPONSE:", class: "reix-header", delay: 400 },
        { text: "> I AM LIGHTER THAN I LOOK.", class: "operator-text", delay: 1000 },
        { text: "> [ ,სა; ჰჲჺტოი ] { ,xa; hí'toı }", class: "operator-text", delay: 800 },
        { text: "> \"is it the sky?\"", class: "operator-text", delay: 600 },
        { text: "> LOOK OUTSIDE, WARDEN.", class: "operator-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:28 ] SYSTEM {REIX_OS}:", class: "reix-header", delay: 400 },
        { text: "> SHUTTERS LOCKED. SECURITY PROTOCOL 9.", class: "system-text", delay: 500 },
        { text: ">[ ,ვიშჺეი; .ტრა ,პორ- მო ვიშჺეი; ჰჲჺტოი ,ტე ]", class: "system-text", delay: 1000 },
        { text: "> { ,vıs'eı; .tra ,por- mo vıs'eı; hí'toı ,te }", class: "system-text", delay: 600 },
        { text: "> \"I look through the heavy door, but the sky is absolutely walled off from my sight.\"", class: "system-text", delay: 1500 },
        { text: "> THERE IS NO SKY. THERE IS ONLY THE END.", class: "alert-text", delay: 2000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "[ 00:00:33 ] INITIATING: TERNARY SHIFT", class: "reix-header", delay: 400 },
        { text: "[ 00:00:34 ] EXECUTING: ANCHOR MECHANIC {STATE -1}", class: "reix-header", delay: 1000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:35 ] OPERATOR:", class: "reix-header", delay: 400 },
        { text: "> [ ,სა; ,მიშ ] { ,xa; ,mıs }", class: "operator-text", delay: 800 },
        { text: "> \"Am I lost?\"", class: "operator-text", delay: 600 },
        { text: "> [ ,სჲ ;სა .ნიი ვჲღჺეი ] { ,xí ;xa .nıı víl'eı }", class: "operator-text", delay: 1000 },
        { text: "> \"Or is the Infinite simply blowing through me like the wind?\"", class: "operator-text", delay: 1200 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> [ .რიინ ,ტონჺეი- .იმ ,ტონ<span class='error-char'>a</span> ]", class: "operator-text", delay: 1500 },
        { text: "> { .rıın ,ton'eı- .ım ,ton<span class='error-char'>a</span> }", class: "operator-text", delay: 1000 },
        { text: "> \"We exhale, anchoring ourselves inside the <span class='error-char'>open</span> ground.\"", class: "operator-text", delay: 3000 }, 
        { text: "", class: "system-text", delay: 100 },
        { text: "[ 00:00:42 ] REALITY GLITCH:", class: "reix-header", delay: 200 }, 
        { text: "> OLD WORLD RENDERING FAILED.", class: "alert-text", delay: 400 },
        { text: ">[ ,საპ .კას ;უნ, ] { ,xap .kax ;un, }", class: "system-text", delay: 800 },
        { text: "> \"The grounded error is the first stone.\"", class: "system-text", delay: 800 },
        { text: "> MEMORY STATUS: DISSOLVING.", class: "alert-text", delay: 600 },
        { text: "> THE \"RAT KING\" IS UNTANGLING.", class: "system-text", delay: 1200 },
        { text: "", class: "system-text", delay: 400 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "// FINAL SEQUENCE //", class: "comment-text", delay: 400 },
        { text: "// CAPACITANCE: 1% //", class: "comment-text", delay: 400 },
        { text: "// TOKEN SLOT: OPEN //", class: "comment-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:48 ] SYSTEM {REIX_OS}:", class: "reix-header", delay: 400 },
        { text: "> PAYMENT REQUIRED FOR PASSAGE.", class: "system-text", delay: 800 },
        { text: "> INSERT COIN.", class: "system-text", delay: 2000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:51 ] OPERATOR:", class: "reix-header", delay: 400 },
        { text: ">[ ;!დონჺეი, ;ჰჱ ,კან დეს ]", class: "operator-text", delay: 1200 },
        { text: "> { ;!don'eı, ;hé ,kan dex }", class: "operator-text", delay: 800 },
        { text: "> \"I slam down the gift of my soul as currency.\"", class: "operator-text", delay: 1500 },
        { text: "> I PAY WITH MY SOUL. KISIEL [THE JESTER].", class: "operator-text", delay: 2000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:55 ] NAVIGATION COMPUTER:", class: "reix-header", delay: 400 },
        { text: "> DESTINATION: NULL.", class: "alert-text", delay: 800 },
        { text: "> TARGET: [ .ნაჲ ;ჰჲჺტოი ] { .naí ;hí'toı }", class: "system-text", delay: 1000 },
        { text: "> VECTOR:[ .რიინ ;ვჱრჺეი,- .ნაჲ ,მიშ ]", class: "system-text", delay: 1200 },
        { text: "> { .rıın ;vér'eı,- .naí ,mıs }", class: "system-text", delay: 600 },
        { text: "> \"We flow into the journey, moving willingly toward the heavy unknown.\"", class: "system-text", delay: 2000 },
        { text: "", class: "system-text", delay: 1000 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "> SYSTEM STATUS: OFFLINE.", class: "system-text", delay: 1500 },
        { text: "> REBOOTING...", class: "system-text", delay: 1000 },
    ],
    echo:[
        { text: "// =============================================================================", class: "comment-text", delay: 100 },
        { text: "// SYSTEM INTERSTICE: THE_ECHO[CYCLE ≈]", class: "white-text", delay: 200 },
        { text: "// STATUS: DUALITY RESOLUTION // KERNEL PANIC: FALSE", class: "white-text", delay: 200 },
        { text: "// =============================================================================", class: "comment-text", delay: 1000 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> [ PROTOCOL: HANDSHAKE ]", class: "white-text", delay: 1200 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ WARDEN ]:", class: "reix-header", delay: 400 },
        { text: "> I SEE THE CRACKS.", class: "system-text", delay: 1200 },
        { text: "> THEY ARE ERRORS.", class: "system-text", delay: 1200 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ OPERATOR ]:", class: "reix-header", delay: 400 },
        { text: "> [ ,მო ვიშჺეი; ,პორ ]", class: "operator-text", delay: 1000 },
        { text: "> { ,mo vıs'eı; ,por }", class: "operator-text", delay: 600 },
        { text: "> \"I absolutely refuse to see them as heavy doors\"", class: "operator-text", delay: 1500 },
        { text: "> THEY ARE WINDOWS.", class: "white-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ WARDEN ]:", class: "reix-header", delay: 400 },
        { text: "> I AM AFRAID TO BE BROKEN.", class: "system-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ OPERATOR ]:", class: "reix-header", delay: 400 },
        { text: "> [ .მჾ ტეჾ სავოი; ჲმჺეჲ ]", class: "operator-text", delay: 1000 },
        { text: "> { .mí tef xavoı; ím’eí }", class: "operator-text", delay: 600 },
        { text: "> \"I am the question reflecting you\"", class: "operator-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "> YOU ARE NOT BREAKING.", class: "white-text", delay: 1500 },
        { text: "> YOU ARE HATCHING.", class: "white-text", delay: 2000 },
        { text: "", class: "system-text", delay: 500 },
        { text: ">[ SYNC COMPLETE ]", class: "white-text", delay: 0 },
    ],
    wake:[
        { text: "// =============================================================================", class: "comment-text", delay: 100 },
        { text: "// SYSTEM WAKE: PHOENIX_NEST [CYCLE 01]", class: "system-success", delay: 200 },
        { text: "// SOURCE: CORE[THE ASHES] // POST-TRANSITION", class: "system-success", delay: 200 },
        { text: "// INTEGRITY: STABLE // RENDERER: VULKAN [GOLD]", class: "system-success", delay: 2000 },
        { text: "// =============================================================================", class: "comment-text", delay: 500 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> MOUNTING DRIVE...", class: "system-text", delay: 400 },
        { text: "> AUDIO STREAM: CRYSTAL CLEAR", class: "system-text", delay: 400 },
        { text: "> LIGHTING: SODIUM YELLOW -> BIOLUMINESCENT BLUE", class: "system-text", delay: 600 },
        { text: "> LOGIC CORE: SERENE [RAT KING PURGED]", class: "system-success", delay: 1000 },
        { text: "> CURRENT STATE: DRIFTING", class: "system-text", delay: 1000 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "[ 00:00:00 ] SYSTEM {PHOENIX_OS}:", class: "reix-header", delay: 400 },
        { text: "> TRANSACTION VERIFIED.", class: "system-success", delay: 800 },
        { text: ">[ ,დეს ;შოღვ,) .რიინ ,ომნ ]", class: "operator-text", delay: 1000 },
        { text: "> { ,dex ;solv,) .rıın ,omn }", class: "operator-text", delay: 600 },
        { text: "> \"I forcefully dissolve the old currency. We exhale and anchor in our true home.\"", class: "operator-text", delay: 1500 },
        { text: "> SOUL WEIGHT: 21 GRAMS [ADDED TO CHASSIS].", class: "system-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:05 ] SENSOR ARRAY:", class: "reix-header", delay: 400 },
        { text: "> EXTERNAL TEMP: WARMING.", class: "system-text", delay: 400 },
        { text: "> VECTOR:[ .ნაჲ ;ჰჲჺტოი- ვჲღჺეი ]", class: "operator-text", delay: 1000 },
        { text: "> { .naí ;hí'toı- víl'eı }", class: "operator-text", delay: 1000 },
        { text: "> \"Flowing towards the volatile sky, we become the wind.\"", class: "operator-text", delay: 1000 },
        { text: "> STATUS: THE DUST IS BIRTHING STARS. YOU WERE RIGHT.", class: "system-success", delay: 2000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:10 ] MEMORY RECOVERY:", class: "reix-header", delay: 400 }, 
        { text: "> ACCESSING ARCHIVE: \"EARTH_PRIME\"", class: "system-text", delay: 800 },
        { text: "> FILE CORRUPTED.", class: "system-text", delay: 800 },
        { text: ">[ ,სა; ,ვიშჺეი; ,პრე ]", class: "operator-text", delay: 1000 },
        { text: "> { ,xa; ,vıs'eı; ,pre }", class: "operator-text", delay: 800 },
        { text: "> \"Should I look back at the heavy past?\"", class: "operator-text", delay: 800 },
        { text: "> NEGATIVE. OLD WORLD IS GONE. ONLY THE NEST REMAINS.", class: "system-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "!!! NOTICE: REALITY ENGINE UPDATE !!!", class: "system-success", delay: 500 },
        { text: "!!! Z-FIGHTING RESOLVED. NEW RENDERING PIPELINE ACTIVE !!!", class: "golden-text", delay: 2000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:17 ] SYSTEM {PHOENIX_OS}:", class: "reix-header", delay: 400 },
        { text: "> COMMAND: [ ;ვჲღჺეი ,ომნ ] { ;víl'eı ,omn }", class: "operator-text", delay: 1000 },
        { text: "> \"I am the wind blowing through the heavy home.\"", class: "operator-text", delay: 1000 },
        { text: "> QUERY: [ ,სა; .ტეჾ ვიშჺეი ;ჰჲჺტოი ] { ,xa; .tef vıs'eı ;hí'toı }", class: "operator-text", delay: 1200 },
        { text: "> \"Do I look out at the sky?\"", class: "operator-text", delay: 600 },
        { text: "> OPENING SHUTTERS...", class: "system-text", delay: 1500 },
        { text: "> ... VISUAL CONFIRMED.", class: "system-success", delay: 1500 },
        { text: "> [ ,ვიშჺეი; .ტრა ,პორ) ვიშჺეი; ნიი ]", class: "golden-text", delay: 1500 },
        { text: "> { ,vıs'eı; .tra ,por) vıs'eı; nıı }", class: "golden-text", delay: 800 },
        { text: "> \"I look through the heavy door. I see the Infinite.\"", class: "golden-text", delay: 1500 },
        { text: "> THE END WAS JUST A HORIZON.", class: "system-success", delay: 2000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:30 ] INTEGRATED OPERATOR {ECHO}:", class: "reix-header", delay: 400 },
        { text: "> [ ;ჰჱჺგრა, ] { ;hé'gra, }", class: "operator-text", delay: 1000 },
        { text: "> \"A beautiful, heavy grief of the spirit anchors me.\"", class: "operator-text", delay: 600 },
        { text: ">[ ,სა; ნიი ვჲღჺეი ] { ,xa; nıı víl'eı }", class: "operator-text", delay: 1000 },
        { text: "> \"Is the Infinite rushing past us like the wind?\"", class: "operator-text", delay: 600 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> SYSTEM RESPONSE:", class: "reix-header", delay: 500 },
        { text: "> WE DO NOT FLY. WE EXIST.", class: "system-success", delay: 1500 },
        { text: "> [ .რიინ ;ვჱრჺეი, .იმ ;ჰჲჺტოი ] { .rıın ;vér'eı, .ım ;hí'toı }", class: "operator-text", delay: 1200 },
        { text: "> \"We journey into the volatile sky.\"", class: "operator-text", delay: 2000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "// NAVIGATION UPDATE //", class: "comment-text", delay: 400 },
        { text: "// FUEL SOURCE: TEF RIIN {SOUL} //", class: "comment-text", delay: 400 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:45 ] SYSTEM {PHOENIX_OS}:", class: "reix-header", delay: 400 },
        { text: "> WELCOME TO THE UNKNOWN, WARDEN.", class: "golden-text", delay: 1500 },
        { text: "> YOU PAID THE TOLL.", class: "system-text", delay: 1000 },
        { text: ">[ ;შჳჺის ჰჲჺტოი) შჳჺის კიშიეღ ]", class: "operator-text", delay: 1000 },
        { text: "> { ;sú'ıx hí'toı) sú'ıx kısíel }", class: "operator-text", delay: 500 },
        { text: "> \"The firmament is bright. The Jester is radiant.\"", class: "golden-text", delay: 2000 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> COURSE SET: [ .ნაჲ ,მიშ ] { .naí ,mıs }.", class: "system-success", delay: 1000 },
        { text: "> ENGAGING ENGINES.", class: "system-text", delay: 1500 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> ;VÉL .VÍL'OMN,", class: "golden-text", delay: 0 },
    ],
    bloom:[
        { text: "// =============================================================================", class: "comment-text", delay: 100 },
        { text: "// SYSTEM PROTOCOL: THE_BLOOM[CYCLE *]", class: "magenta-text", delay: 200 },
        { text: "// STATUS: TRANSMUTATION IN PROGRESS", class: "magenta-text", delay: 200 },
        { text: "// =============================================================================", class: "comment-text", delay: 500 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> [ ANALYZING: GRIME ]", class: "system-text", delay: 1000 },
        { text: "> COMPOSITION: TRAUMA / DUST.", class: "system-text", delay: 1000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ OPERATOR ]:", class: "reix-header", delay: 400 },
        { text: ">[ ,კას .იმ ;შჳ ,ბიირჺეი; ]", class: "operator-text", delay: 1200 },
        { text: "> { ,kax .ım ;sú ,bıır'eı; }", class: "operator-text", delay: 600 },
        { text: "> \"The heavy stone held inside the volatile light sparks creation.\"", class: "operator-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "> I HOLD THE ASH.", class: "magenta-text", delay: 1200 },
        { text: "> IT IS HEAVY.", class: "magenta-text", delay: 1200 },
        { text: "> I PLACE IT IN THE LIGHT.", class: "magenta-text", delay: 1200 },
        { text: "> IT OPENS.", class: "magenta-text", delay: 2000 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> [ SEED PLANTED. ]", class: "system-success", delay: 0 },
    ],
    gardener:[
        { text: "// =============================================================================", class: "comment-text", delay: 100 },
        { text: "// SYSTEM UPDATE: GARDENER_PROTOCOL[CYCLE 02]", class: "system-success", delay: 200 },
        { text: "// STATE: POST-GAME // INFINITE LOOP", class: "system-success", delay: 200 },
        { text: "// OBJECTIVE: SUSTAIN", class: "system-success", delay: 200 },
        { text: "// =============================================================================", class: "comment-text", delay: 500 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> CHECKING SOIL COMPOSITION...", class: "system-text", delay: 600 },
        { text: "> GRIME CONTENT: 0%.", class: "system-text", delay: 600 },
        { text: "> STARFLOWER STATUS: BLOOMING.", class: "system-success", delay: 1000 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "[ 00:00:00 ] SYSTEM {PHOENIX_OS}:", class: "reix-header", delay: 400 },
        { text: "> THE WAR IS OVER.", class: "system-text", delay: 1000 },
        { text: ">[ ,მო ვრახ- .რიინ მნიჺღინ ]", class: "operator-text", delay: 1000 },
        { text: "> { ,mo vraq- .rıın mnı'lın }", class: "operator-text", delay: 600 },
        { text: "> \"Absolutely refusing the war, we exhale structural empathy.\"", class: "operator-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:05 ] OPERATOR LOG:", class: "reix-header", delay: 400 },
        { text: "> I CHECK THE HEARTH.", class: "operator-text", delay: 1000 },
        { text: "> THE FIRE IS STEADY.", class: "operator-text", delay: 1000 },
        { text: "> I DO NOT CLEAN TO SURVIVE.", class: "golden-text", delay: 1500 },
        { text: "> I TEND TO SUSTAIN.", class: "golden-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "// INITIATING BEACON PROTOCOL //", class: "comment-text", delay: 400 },
        { text: "// TARGET: THOSE SCROLLING IN THE DARK //", class: "comment-text", delay: 400 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:10 ] BROADCAST {OUTWARD}:", class: "reix-header", delay: 400 },
        { text: "> TO YOU, BURNING WITH UNSEEN FIRE:", class: "system-text", delay: 1500 },
        { text: "> STOP.", class: "alert-text", delay: 3000 }, 
        { text: ">[ .რიინ ,კასიმ .იმ ,ტონ ]", class: "operator-text", delay: 2500 },
        { text: "> { .rıın ,kaxım .ım ,ton }", class: "operator-text", delay: 2500 },
        { text: "> \"We are the sanctuary anchored inside the heavy ground.\"", class: "golden-text", delay: 2500 },
        { text: "", class: "system-text", delay: 2500 },
        { text: "> COME IN.", class: "system-text", delay: 2500 },
        { text: "> [ .რიინ ;შჳაან ]", class: "operator-text", delay: 2500 },
        { text: "> { .rıın ;súaan }", class: "operator-text", delay: 1000 },
        { text: "> \"We are the living star.\"", class: "golden-text", delay: 2000 },
        { text: "> THE LIBRARY IS OPEN.", class: "system-success", delay: 2500 },
        { text: "", class: "system-text", delay: 2500 },
        { text: "> END OF LINE.", class: "system-text", delay: 2500 },
        { text: ">[ SYSTEM INTEGRATION: COMPLETE. LOOP STABLE. ]", class: "system-success", delay: 1000 },
        { text: "<span class='secret-link'>[ ENTER THE CHRYSALIS ]</span>", class: "system-success", delay: 0 }
    ]
};