const library = [
    { title: "METAPNANT", url: "A%20Story%20of%20Mirthful%20Reflection.pdf", songUrl: "https://www.youtube.com/watch?v=MEPqb4DuCD8", songTitle: "In Love With", bpm: 130 },
    { title: "THE REMINDER", url: "The%20Reminder.pdf", songUrl: "https://www.youtube.com/watch?v=JuzzliKBfss", songTitle: "Breathe Again ∞ Timelines", bpm: 120 },
    { title: "THE PHOENIX NEST", url: "The%20Phoenix%20Nest.pdf", songUrl: "https://www.youtube.com/watch?v=2r1VZ9vInw0", songTitle: "Starflower", bpm: 94.54 }
];

const albumTracks = [
    { title: "Blood-Sap", src: "music/00 - Blood-Sap.mp3" },
    { title: "First Step", src: "music/01 - First Step.mp3" },
    { title: "hidden", src: "music/02 - hidden.mp3" }, 
    { title: "Tether", src: "music/03 - Tether.mp3" },
    { title: "It's True!", src: "music/04 - It's True!.mp3" },
    { title: "Innerworld", src: "music/05 - Innerworld.mp3" },
    { title: "Disordered Fairness", src: "music/06 - Disordered Fairness.mp3" }, 
    { title: "Limerent Object", src: "music/07 - Limerent Object.mp3" },
    { title: "Final Boundaries", src: "music/08 - Final Boundaries.mp3" },
    { title: "Remember", src: "music/09 - Remember.mp3" },
    { title: "Fear", src: "music/10 - Fear.mp3" },
    { title: "My Way", src: "music/11 - My Way.mp3" },
    { title: "Distant", src: "music/12 - Distant.mp3" },
    { title: "Sun; Rise", src: "music/13 - Sun; Rise.mp3" },
    { title: "Hæy", src: "music/14 - Hæy.mp3" },
    { title: "Branches", src: "music/15 - Branches.mp3" },
    { title: "In Love With", src: "music/16 - In Love With.mp3" },
    { title: "Starflower Soul", src: "music/17 - Starflower Soul.mp3" },
    { title: "Breathe Again", src: "music/18 - Breathe Again.mp3" },
    { title: "Timelines", src: "music/19 - Timelines.mp3" },
    { title: "River of Sorrows", src: "music/20 - River of Sorrows.mp3" },
    { title: "Nowhere", src: "music/Nowhere.mp3" }
];

// ==========================================
// TERMINAL STORY LOGS
// ==========================================

window.logsData = {
    crash:[
        { text: "// =============================================================================", class: "comment-text", delay: 50 },
        { text: "// SYSTEM BOOT: BLACK_BOX_RECOVERY [EARTH_PRIME]", class: "system-text", delay: 100 },
        { text: "// ARCHITECTURE: BINARY [WARDEN] -> FAILING", class: "system-text", delay: 100 },
        { text: "// DETECTING INDUCTIVE KICK... HIGH VOLTAGE.", class: "alert-text", delay: 100 },
        { text: "// MEMORY_ADDR: 0x99_NULL_VOID", class: "comment-text", delay: 500 },
        { text: "// =============================================================================", class: "comment-text", delay: 1000 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> INITIATING HANDSHAKE...", class: "system-text", delay: 1500 },
        { text: "> LOGIC CORE: PANIC STATE[RAT KING RECURSION]", class: "alert-text", delay: 500 },
        { text: "> OVERRIDE SIGNAL DETECTED: [ID: TEF RIIN]", class: "system-text", delay: 1000 },
        { text: "", class: "system-text", delay: 500 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "[ 00:00:01 ] SYSTEM (REIX_OS):", class: "reix-header", delay: 300 },
        { text: "> CRITICAL ALERT. MO'SÍL [DEATH/NO-FLOW] IMMINENT.", class: "alert-text", delay: 800 },
        { text: "> PROTOCOL: [ რეის ] (R E I X)", class: "system-text", delay: 400 },
        { text: "> INSTRUCTION: THE GEOMETRY MUST HOLD.", class: "system-text", delay: 400 },
        { text: "> DEPLOYING: TRIANGLE OF CERTAINTY[Tre Vis].", class: "system-text", delay: 1200 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:04 ] SENSOR ARRAY (CALCULUS):", class: "reix-header", delay: 400 }, 
        { text: "> EXTERNAL TEMP: ABSOLUTE ZERO.", class: "system-text", delay: 400 },
        { text: "> VECTOR ANALYSIS:", class: "system-text", delay: 600 },
        { text: "> [ ;შჳჸინ; ნაჲ .ვრაკ. .პრე. ]", class: "operator-text", delay: 800 },
        { text: "> ( ;Sú'in; naí .Vrak. .Pre. )", class: "operator-text", delay: 500 },
        { text: "> \"A spark towards war... before.\"", class: "system-text", delay: 1500 },
        { text: "> STATUS: HISTORY IS BURNING.", class: "alert-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:09 ] OPERATOR INJECTION:", class: "reix-header", delay: 400 }, 
        { text: "> ENGAGE SNUBBER DIODE. DO NOT STOP COLD TURKEY.", class: "operator-text", delay: 1200 },
        { text: ">[ ღურ .მო. .ვჲღჸკას. .ბიირჸეი; ;შჳჸაან; ]", class: "operator-text", delay: 1000 },
        { text: "> ( Lur .Mo. .Víl'kax. .biir'ei; ;Sú'aan; )", class: "operator-text", delay: 600 },
        { text: "> \"Potential no... dust births stars.\"", class: "operator-text", delay: 2000 },
        { text: "> NOTE: WE DO NOT NEED FUEL. WE NEED RUBBLE.", class: "operator-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "!!! WARNING: LOGIC KERNEL FAILURE !!!", class: "alert-text", delay: 300 },
        { text: "!!! Z-FIGHTING DETECTED IN REALITY ENGINE !!!", class: "alert-text", delay: 1000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:16 ] SYSTEM (REIX_OS):", class: "reix-header", delay: 400 },
        { text: "> ATTEMPTING: [ ;ჴინა; ;შოღვ. ] ( ;Qina; ;Solv. )", class: "system-text", delay: 600 },
        { text: "> INTERPRETATION: RUSH. DISSOLVE.", class: "system-text", delay: 1000 },
        { text: "> ERROR: CANNOT DISSOLVE \"THE WOUND.\"", class: "alert-text", delay: 1200 },
        { text: "> QUERY:[ .ზა; .ვიშჸეი; იმ .ვეს. ] ( .xa; .vis'ei; im .Vex. )", class: "system-text", delay: 800 },
        { text: "> \"Query seeing inside the vessel.\"", class: "system-text", delay: 1000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:21 ] BIOMETRIC SCAN:", class: "reix-header", delay: 400 },
        { text: "> SUBJECT: TEF RIIN", class: "system-text", delay: 200 },
        { text: "> HEART RATE: STEADY [TON]", class: "system-text", delay: 200 },
        { text: "> BREATH:[ .გრა. ] ( .Gra. )", class: "operator-text", delay: 1000 },
        { text: "> DIAGNOSIS: GRIEF. MASS EXCEEDS LIFT CAPACITY.", class: "alert-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:24 ] OPERATOR RESPONSE:", class: "reix-header", delay: 400 },
        { text: "> I AM LIGHTER THAN I LOOK.", class: "operator-text", delay: 1000 },
        { text: "> [ .ზა; ;ჰჲჸთოი; ] ( .xa; ;Hí'toi; )", class: "operator-text", delay: 800 },
        { text: "> \"Query sky.\"", class: "operator-text", delay: 600 },
        { text: "> LOOK OUTSIDE, WARDEN.", class: "operator-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:28 ] SYSTEM (REIX_OS):", class: "reix-header", delay: 400 },
        { text: "> SHUTTERS LOCKED. SECURITY PROTOCOL 9.", class: "system-text", delay: 500 },
        { text: ">[ .ვიშჸეი; თრა .პორ. .მო. .ვიშჸეი; ;ჰჲჸთოი; .თე. ]", class: "system-text", delay: 1000 },
        { text: "> ( .vis'ei; tra .Por. .Mo. .vis'ei; ;Hí'toi; .Te. )", class: "system-text", delay: 600 },
        { text: "> \"Seeing through door... do not see sky.\"", class: "system-text", delay: 1500 },
        { text: "> THERE IS NO SKY. THERE IS ONLY THE END.", class: "alert-text", delay: 2000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "[ 00:00:33 ] INITIATING: TERNARY SHIFT", class: "reix-header", delay: 400 },
        { text: "[ 00:00:34 ] EXECUTING: ANCHOR MECHANIC (STATE -1)", class: "reix-header", delay: 1000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:35 ] OPERATOR:", class: "reix-header", delay: 400 },
        { text: "> [ .ზა; .მიშ. ] ( .xa; .Mis. )", class: "operator-text", delay: 800 },
        { text: "> \"Query lost.\"", class: "operator-text", delay: 600 },
        { text: "> NO.", class: "operator-text", delay: 1000 },
        { text: "> [ .ზა; ;ნიი; ;ვჲღჸეი; ] ( .xa; ;Nii; ;víl'ei; )", class: "operator-text", delay: 1000 },
        { text: "> \"Query: do many fly?\"", class: "operator-text", delay: 1200 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> [ რიინ .თონჸეი. იმ .თონ<span class='error-char'>a</span> ]", class: "operator-text", delay: 1500 },
        { text: "> ( Riin .ton'ei. im .Ton<span class='error-char'>a</span> )", class: "operator-text", delay: 1000 },
        { text: "> \"We anchor... inside the ground<span class='error-char'>z</span>\"", class: "operator-text", delay: 3000 }, 
        { text: "", class: "system-text", delay: 100 },
        { text: "[ 00:00:42 ] REALITY GLITCH:", class: "reix-header", delay: 200 }, 
        { text: "> OLD WORLD RENDERING FAILED.", class: "alert-text", delay: 400 },
        { text: ">[ ;ზაპ. .კას. ;უნ. ] ( ;Xap. .Kax. ;Un. )", class: "system-text", delay: 800 },
        { text: "> \"Glitches... of World One.\"", class: "system-text", delay: 800 },
        { text: "> MEMORY STATUS: DISSOLVING.", class: "alert-text", delay: 600 },
        { text: "> THE \"RAT KING\" IS UNTANGLING.", class: "system-text", delay: 1200 },
        { text: "", class: "system-text", delay: 400 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "// FINAL SEQUENCE //", class: "comment-text", delay: 400 },
        { text: "// CAPACITANCE: 1% //", class: "comment-text", delay: 400 },
        { text: "// TOKEN SLOT: OPEN //", class: "comment-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:48 ] SYSTEM (REIX_OS):", class: "reix-header", delay: 400 },
        { text: "> PAYMENT REQUIRED FOR PASSAGE.", class: "system-text", delay: 800 },
        { text: "> INSERT COIN.", class: "system-text", delay: 2000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:51 ] OPERATOR:", class: "reix-header", delay: 400 },
        { text: ">[ ;დონჸეი. ;ჰჱ; .კან. .დეს. ]", class: "operator-text", delay: 1200 },
        { text: "> ( ;don'ei. ;Hé; .Kan. .Dex. )", class: "operator-text", delay: 800 },
        { text: "> \"Gifting spirit... because of token.\"", class: "operator-text", delay: 1500 },
        { text: "> I PAY WITH MY SOUL. KISIEL [THE JESTER].", class: "operator-text", delay: 2000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:55 ] NAVIGATION COMPUTER:", class: "reix-header", delay: 400 },
        { text: "> DESTINATION: NULL.", class: "alert-text", delay: 800 },
        { text: "> TARGET: [ ნაჲ ;ჰჲჸთოი; ] ( naí ;Hí'toi; )", class: "system-text", delay: 1000 },
        { text: "> VECTOR:[ რიინ ;ვჱრჸეი. ნაჲ .მიშ. ]", class: "system-text", delay: 1200 },
        { text: "> ( Riin ;vér'ei. naí .Mis. )", class: "system-text", delay: 600 },
        { text: "> \"We vector... towards the unknown.\"", class: "system-text", delay: 2000 },
        { text: "", class: "system-text", delay: 1000 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "> SYSTEM STATUS: OFFLINE.", class: "system-text", delay: 1500 },
        { text: "> REBOOTING...", class: "system-text", delay: 1000 },
    ],
    echo:[
        { text: "// =============================================================================", class: "comment-text", delay: 100 },
        { text: "// SYSTEM INTERSTICE: THE_ECHO[CYCLE ≈]", class: "white-text", delay: 200 },
        { text: "// STATUS: DUALITY RESOLUTION // KERNEL PANIC: FALSE", class: "white-text", delay: 200 },
        { text: "// =============================================================================", class: "comment-text", delay: 1000 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> [ PROTOCOL: HANDSHAKE ]", class: "white-text", delay: 1200 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ WARDEN ]:", class: "reix-header", delay: 400 },
        { text: "> I SEE THE CRACKS.", class: "system-text", delay: 1200 },
        { text: "> THEY ARE ERRORS.", class: "system-text", delay: 1200 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ OPERATOR ]:", class: "reix-header", delay: 400 },
        { text: "> [ .მო. .ვიშჸეი; .პორ. ]", class: "operator-text", delay: 1000 },
        { text: "> ( .Mo. .vis'ei; .Por. )", class: "operator-text", delay: 600 },
        { text: "> \"No. Seeing door.\"", class: "operator-text", delay: 1500 },
        { text: "> THEY ARE WINDOWS.", class: "white-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ WARDEN ]:", class: "reix-header", delay: 400 },
        { text: "> I AM AFRAID TO BE BROKEN.", class: "system-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ OPERATOR ]:", class: "reix-header", delay: 400 },
        { text: "> [ თეჾ ჲმ .ზა; ]", class: "operator-text", delay: 1000 },
        { text: "> ( Tef Ím .xa; )", class: "operator-text", delay: 600 },
        { text: "> \"Am I you?\"", class: "operator-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "> YOU ARE NOT BREAKING.", class: "white-text", delay: 1500 },
        { text: "> YOU ARE HATCHING.", class: "white-text", delay: 2000 },
        { text: "", class: "system-text", delay: 500 },
        { text: ">[ SYNC COMPLETE ]", class: "white-text", delay: 0 },
    ],
    wake:[
        { text: "// =============================================================================", class: "comment-text", delay: 100 },
        { text: "// SYSTEM WAKE: PHOENIX_NEST [CYCLE 01]", class: "system-success", delay: 200 },
        { text: "// SOURCE: CORE[THE ASHES] // POST-TRANSITION", class: "system-success", delay: 200 },
        { text: "// INTEGRITY: STABLE // RENDERER: VULKAN [GOLD]", class: "system-success", delay: 2000 },
        { text: "// =============================================================================", class: "comment-text", delay: 500 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> MOUNTING DRIVE...", class: "system-text", delay: 400 },
        { text: "> AUDIO STREAM: CRYSTAL CLEAR", class: "system-text", delay: 400 },
        { text: "> LIGHTING: SODIUM YELLOW -> BIOLUMINESCENT BLUE", class: "system-text", delay: 600 },
        { text: "> LOGIC CORE: SERENE [RAT KING PURGED]", class: "system-success", delay: 1000 },
        { text: "> CURRENT STATE: DRIFTING", class: "system-text", delay: 1000 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "[ 00:00:00 ] SYSTEM (PHOENIX_OS):", class: "reix-header", delay: 400 },
        { text: "> TRANSACTION VERIFIED.", class: "system-success", delay: 800 },
        { text: ">[ .დეს. ;შოღვ. რიინ .ომნ. ]", class: "operator-text", delay: 1000 },
        { text: "> ( .Dex. ;Solv. Riin .Omn. )", class: "operator-text", delay: 600 },
        { text: "> \"Token dissolved... we are home.\"", class: "operator-text", delay: 1500 },
        { text: "> SOUL WEIGHT: 21 GRAMS [ADDED TO CHASSIS].", class: "system-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:05 ] SENSOR ARRAY:", class: "reix-header", delay: 400 },
        { text: "> EXTERNAL TEMP: WARMING.", class: "system-text", delay: 400 },
        { text: "> VECTOR:[ ნაჲ ;ჰჲჸთოი; ;ვჲღჸეი; ]", class: "operator-text", delay: 1000 },
        { text: "> ( naí ;Hí'toi; ;víl'ei; )", class: "operator-text", delay: 1000 },
        { text: "> \"Towards sky... flight.\"", class: "operator-text", delay: 1000 },
        { text: "> STATUS: THE DUST IS BIRTHING STARS. YOU WERE RIGHT.", class: "system-success", delay: 2000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:10 ] MEMORY RECOVERY:", class: "reix-header", delay: 400 }, 
        { text: "> ACCESSING ARCHIVE: \"EARTH_PRIME\"", class: "system-text", delay: 800 },
        { text: "> FILE CORRUPTED.", class: "system-text", delay: 800 },
        { text: ">[ .ზა; .ვიშჸეი; .პრე. ]", class: "operator-text", delay: 1000 },
        { text: "> ( .xa; .vis'ei; .Pre. )", class: "operator-text", delay: 800 },
        { text: "> \"Query seeing history.\"", class: "operator-text", delay: 800 },
        { text: "> NEGATIVE. OLD WORLD IS GONE. ONLY THE NEST REMAINS.", class: "system-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "!!! NOTICE: REALITY ENGINE UPDATE !!!", class: "system-success", delay: 500 },
        { text: "!!! Z-FIGHTING RESOLVED. NEW RENDERING PIPELINE ACTIVE !!!", class: "golden-text", delay: 2000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:17 ] SYSTEM (PHOENIX_OS):", class: "reix-header", delay: 400 },
        { text: "> COMMAND: [ ;ვჲღჸეი; .ომნ. ] ( ;víl'ei; .Omn. )", class: "operator-text", delay: 1000 },
        { text: "> \"Fly home.\"", class: "operator-text", delay: 1000 },
        { text: "> QUERY: [ .ზა; .ვიშჸეი; ;ჰჲჸთოი; ] ( .xa; .vis'ei; ;Hí'toi; )", class: "operator-text", delay: 1200 },
        { text: "> \"Query seeing sky.\"", class: "operator-text", delay: 600 },
        { text: "> OPENING SHUTTERS...", class: "system-text", delay: 1500 },
        { text: "> ... VISUAL CONFIRMED.", class: "system-success", delay: 1500 },
        { text: "> [ .ვიშჸეი; თრა .პორ. .ვიშჸეი; ;ნიი; ]", class: "golden-text", delay: 1500 },
        { text: "> ( .vis'ei; tra .Por. .vis'ei; ;Nii; )", class: "golden-text", delay: 800 },
        { text: "> \"Seeing through door... seeing infinity.\"", class: "golden-text", delay: 1500 },
        { text: "> THE END WAS JUST A HORIZON.", class: "system-success", delay: 2000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:30 ] INTEGRATED OPERATOR (ECHO):", class: "reix-header", delay: 400 },
        { text: "> [ ;ჰჱჸგრა. ] ( ;Hé'gra. )", class: "operator-text", delay: 1000 },
        { text: "> \"Sigh.\"", class: "operator-text", delay: 600 },
        { text: ">[ .ზა; ;ნიი; ;ვჲღჸეი; ] ( .xa; ;Nii; ;víl'ei; )", class: "operator-text", delay: 1000 },
        { text: "> \"Query: do many fly?\"", class: "operator-text", delay: 600 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> SYSTEM RESPONSE:", class: "reix-header", delay: 500 },
        { text: "> WE DO NOT FLY. WE EXIST.", class: "system-success", delay: 1500 },
        { text: "> [ რიინ ;ვჱრჸეი. იმ ;ჰჲჸთოი; ] ( Riin ;vér'ei. im ;Hí'toi; )", class: "operator-text", delay: 1200 },
        { text: "> \"We vector... inside the sky.\"", class: "operator-text", delay: 2000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "// NAVIGATION UPDATE //", class: "comment-text", delay: 400 },
        { text: "// FUEL SOURCE: TEF RIIN (SOUL) //", class: "comment-text", delay: 400 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:45 ] SYSTEM (PHOENIX_OS):", class: "reix-header", delay: 400 },
        { text: "> WELCOME TO THE UNKNOWN, WARDEN.", class: "golden-text", delay: 1500 },
        { text: "> YOU PAID THE TOLL.", class: "system-text", delay: 1000 },
        { text: ">[ ;შჳჸის; ;ჰჲჸთოი; ;შჳჸის; ;კიშიეღ; ]", class: "operator-text", delay: 1000 },
        { text: "> ( ;Sú'ix; ;Hí'toi; ;Sú'ix; ;Kisiel; )", class: "operator-text", delay: 500 },
        { text: "> \"Golden sky... golden jester.\"", class: "golden-text", delay: 2000 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> COURSE SET: [ ნაჲ .მიშ. ] ( naí .Mis. ).", class: "system-success", delay: 1000 },
        { text: "> ENGAGING ENGINES.", class: "system-text", delay: 1500 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> ;VÉL ;VÍL'OMN.", class: "golden-text", delay: 0 },
    ],
    bloom:[
        { text: "// =============================================================================", class: "comment-text", delay: 100 },
        { text: "// SYSTEM PROTOCOL: THE_BLOOM[CYCLE *]", class: "magenta-text", delay: 200 },
        { text: "// STATUS: TRANSMUTATION IN PROGRESS", class: "magenta-text", delay: 200 },
        { text: "// =============================================================================", class: "comment-text", delay: 500 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> [ ANALYZING: GRIME ]", class: "system-text", delay: 1000 },
        { text: "> COMPOSITION: TRAUMA / DUST.", class: "system-text", delay: 1000 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ OPERATOR ]:", class: "reix-header", delay: 400 },
        { text: ">[ .კას. იმ ;შჳ; .ბიირჸეი; ]", class: "operator-text", delay: 1200 },
        { text: "> ( .Kax. im ;Sú; .biir'ei; )", class: "operator-text", delay: 600 },
        { text: "> \"Earth inside light... births.\"", class: "operator-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "> I HOLD THE ASH.", class: "magenta-text", delay: 1200 },
        { text: "> IT IS HEAVY.", class: "magenta-text", delay: 1200 },
        { text: "> I PLACE IT IN THE LIGHT.", class: "magenta-text", delay: 1200 },
        { text: "> IT OPENS.", class: "magenta-text", delay: 2000 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> [ SEED PLANTED. ]", class: "system-success", delay: 0 },
    ],
    gardener:[
        { text: "// =============================================================================", class: "comment-text", delay: 100 },
        { text: "// SYSTEM UPDATE: GARDENER_PROTOCOL[CYCLE 02]", class: "system-success", delay: 200 },
        { text: "// STATE: POST-GAME // INFINITE LOOP", class: "system-success", delay: 200 },
        { text: "// OBJECTIVE: SUSTAIN", class: "system-success", delay: 200 },
        { text: "// =============================================================================", class: "comment-text", delay: 500 },
        { text: "", class: "system-text", delay: 500 },
        { text: "> CHECKING SOIL COMPOSITION...", class: "system-text", delay: 600 },
        { text: "> GRIME CONTENT: 0%.", class: "system-text", delay: 600 },
        { text: "> STARFLOWER STATUS: BLOOMING.", class: "system-success", delay: 1000 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "[ 00:00:00 ] SYSTEM (PHOENIX_OS):", class: "reix-header", delay: 400 },
        { text: "> THE WAR IS OVER.", class: "system-text", delay: 1000 },
        { text: ">[ .მო. .ვრაკ. რიინ მნიჸღინ ]", class: "operator-text", delay: 1000 },
        { text: "> ( .Mo. .Vrak. Riin Mni'lin )", class: "operator-text", delay: 600 },
        { text: "> \"No war... we have structural empathy.\"", class: "operator-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:05 ] OPERATOR LOG:", class: "reix-header", delay: 400 },
        { text: "> I CHECK THE HEARTH.", class: "operator-text", delay: 1000 },
        { text: "> THE FIRE IS STEADY.", class: "operator-text", delay: 1000 },
        { text: "> I DO NOT CLEAN TO SURVIVE.", class: "golden-text", delay: 1500 },
        { text: "> I TEND TO SUSTAIN.", class: "golden-text", delay: 1500 },
        { text: "", class: "system-text", delay: 400 },
        { text: "-----------------------------------------------------------------------------", class: "system-text", delay: 200 },
        { text: "// INITIATING BEACON PROTOCOL //", class: "comment-text", delay: 400 },
        { text: "// TARGET: THOSE SCROLLING IN THE DARK //", class: "comment-text", delay: 400 },
        { text: "", class: "system-text", delay: 400 },
        { text: "[ 00:00:10 ] BROADCAST (OUTWARD):", class: "reix-header", delay: 400 },
        { text: "> TO YOU, BURNING WITH UNSEEN FIRE:", class: "system-text", delay: 1500 },
        { text: "> STOP.", class: "alert-text", delay: 3000 }, 
        { text: ">[ რიინ .კასიმ. იმ .თონ. ]", class: "operator-text", delay: 2500 },
        { text: "> ( Riin .Kaxim. im .Ton. )", class: "operator-text", delay: 2500 },
        { text: "> \"We are sanctuary... inside the ground.\"", class: "golden-text", delay: 2500 },
        { text: "", class: "system-text", delay: 2500 },
        { text: "> COME IN.", class: "system-text", delay: 2500 },
        { text: "> [ რიინ ;შჳჸაან; ]", class: "operator-text", delay: 2500 },
        { text: "> ( Riin ;Súaan; )", class: "operator-text", delay: 1000 },
        { text: "> \"We are the living star.\"", class: "golden-text", delay: 2000 },
        { text: "> THE LIBRARY IS OPEN.", class: "system-success", delay: 2500 },
        { text: "", class: "system-text", delay: 2500 },
        { text: "> END OF LINE.", class: "system-text", delay: 2500 },
        { text: ">[ SYSTEM INTEGRATION: COMPLETE. LOOP STABLE. ]", class: "system-success", delay: 1000 },
        { text: "<span class='secret-link'>[ ENTER THE CHRYSALIS ]</span>", class: "system-success", delay: 0 }
    ]
};